# Base: https://github.com/readthedocs/test-builds/blob/mkdocs-material/mkdocs.yml .

site_name: ZScript Russian Manual
site_description: Русскоязычное руководство по ZScript

site_url: !ENV READTHEDOCS_CANONICAL_URL

repo_url: https://github.com/LLDM-Doom-Modding/zscript_rus_manual/
docs_dir: manual

exclude_docs:
  InternalNotes.md


# General navigation. Overrides auto-collected navigation tree.
#nav:
#- Главная страница: index.md
#- Работа со строками: basics-and-syntax/1.08_rabota_so_strokami.md


# Set the site URL by using a Read the Docs environment variable:
# https://docs.readthedocs.io/en/stable/reference/environment-variables.html


theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: material
  language: ru
  features:
    - navigation.instant

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    # Palette toggle for dark (default) mode:
    - scheme : slate
      primary: indigo
      toggle :
        icon : material/brightness-4
        name : Switch to light mode

    # Palette toggle for light mode:
    - scheme : default
      primary: black
      toggle :
        icon : material/brightness-7
        name : Switch to dark mode

  # Custom page 404. https://github.com/squidfunk/mkdocs-material/discussions/5018
  custom_dir: theme_overrides
  static_template:
    - 404.html


extra_css:
  - extra-stylesheets.css

#extra_javascript:
#  - javascript/readthedocs.js


# Primarily from https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - abbr
  - admonition
  - def_list
  - tables


plugins:
  - search
#  - gen-files:
#      scripts:
#        - generate-toc.py
